## Bug Report

**Describe the Bug:**
A clear and concise description of what the bug is.

**Steps to Reproduce:**

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

**Expected Behavior:**
A clear and concise description of what you expected to happen.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**Additional Information:**

- Operating System: [e.g., Windows]
- Browser (if applicable): [e.g., Chrome]

**Labels:** [optional, specify labels to be applied]

**Assignees:** [optional, specify who should be assigned to this issue]
